user_valid:
  max_length_name: 50
  max_length_email: 255
  min_length_password: 6
user_helper:
  size_gravater: 80
  size_gravater_custom: 50git
checkbox: "1"
configure:
  email:
    owner: "noreply@example.com"
